//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// LET_AlignClient.rc에서 사용되고 있습니다.
//
#define ID_BTN_CLEAR                    3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FPS_CLIENT_DIALOG           102
#define IDS_COMPILE_VER                 102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_AN_ENGINEERING_CALCULATOR   103
#define IDD_PANE_HEADER                 104
#define IDD_PANE_MANUAL                 105
#define IDD_FORM_MAIN                   106
#define IDD_FORM_CAMERA                 107
#define IDD_FORM_MACHINE                108
#define IDD_FORM_MODEL                  109
#define IDD_PANE_CAMERA                 110
#define IDD_PANE_MODEL                  111
#define IDD_PANE_AUTO                   112
#define IDD_PANE_MACHINE                113
#define IDD_PANE_BOTTOM                 115
#define IDD_DLG_VIEWER                  116
#define IDD_DLG_SEARCH_VIEW             117
#define IDD_SHEET_CALIPER_RESULT        120
#define IDD_DLG_MARK_COPY               121
#define IDD_DLG_INI_SETTING             123
#define IDR_MAINFRAME                   128
#define IDD_ONSCREENKEYBOARD_DIALOG     130
#define IDR_MENU1                       132
#define IDD_DIALOG1                     133
#define IDD_DIALOG_PROFILE              133
#define IDD_DLG_RESULT_GRAPH            134
#define IDR_DOGUBAR                     134
#define IDD_DIALOG_MASKING              135
#define IDB_BITMAP1                     136
#define IDB_PNG_CENTER_LINE             137
#define IDB_PNG_RULER                   138
#define IDB_PNG_ZOOM_DEFAULT            139
#define IDB_PNG_ZOOM_FIT                140
#define IDB_PNG_ZOOM_IN                 141
#define IDB_PNG_ZOOM_OUT                142
#define IDB_PNG1                        145
#define IDB_PNG_ZOOM2                   145
#define IDB_PNG_OVERLAY                 146
#define IDD_TAB_TRAIN                   151
#define IDD_TAB_PANE_CAMERA             151
#define IDB_BMP_LOADING                 166
#define IDR_TOOLBAR1                    170
#define IDD_DIALOG_KEYPAD               180
#define IDR_CONTROL_TOOLBAR             182
#define IDD_DLG_SET_INSPPARA            190
#define IDD_DIALOG_PF_SCALE_CALC        195
#define IDD_DIALOG2                     200
#define IDD_IMAGE_VIEWER                200
#define IDD_DLG_IMAGE_PROCESSING        202
#define IDD_DIALOG_MSG                  320
#define IDD_DLG_CREATE_MODEL            321
#define IDD_DLG_MESSAGE                 323
#define IDD_DLG_MASK_MARKVIEW           326
#define IDD_CRAMERSRULE_DIALOG          327
#define IDD_DLG_MANUAL_INPUT_MARK       328
#define IDD_DLG_MESSAGE1                329
#define IDD_VIRTUAL_KEYBOARD_DIALOG     329
#define IDD_DLG_MESSAGE_MODALESS        330
#define IDD_SHEET_CALIPER_PARAM         331
#define IDD_DLG_CALIPER                 332
#define IDD_FORM_PLC_INTERFACE          333
#define IDD_TAB_PANE_CAMERA2            333
#define IDD_TAB_PANE_INSP               334
#define IDD_TAB_PANE_MACHINE            335
#define IDD_TAB_MODEL_ALGORITHM         336
#define IDD_DIALOG_SEARCH_TESTER        337
#define IDD_TAB_PANE_MACHINE2           337
#define IDD_PANE_BOTTOM2                337
#define IDD_DIALOG_SEARCH               338
#define IDD_DIALOG_FINDING              339
#define IDD_PANE_BOTTOM1                340
#define IDD_PANE_BOTTOM_SIMULATION      340
#define IDD_PANE_MACHINE1               341
#define IDD_DIALOG_CAMLIGHT_CONTROL     341
#define IDD_FORM_SYSTEM_OPTION          342
#define IDD_PANE_SIMULATION1            343
#define IDD_PANE_SIMULATION             344
#define IDD_FORM_TREND                  345
#define IDD_TAB_PANE_TREND_REPORT       346
#define IDD_OFFSET_DIALOG               347
#define IDD_DIALOG_OFFSET               347
#define IDD_DIALOG_LIST                 348
#define IDD_DLG_LOGIN                   349
#define IDD_DLG_ALARM                   350
#define IDD_DLG_MANUAL_INPUT_MARK2      350
#define IDD_DLG_MANUAL_INPUT_MARK_1CAM  351
#define IDD_DLG_SELECT_JOB              352
#define IDD_DIALOG_SDV_VAT_SIMULATOR    353
#define IDD_DIALOG_SCATTER              354
#define IDC_PANEL_HEADER                1000
#define IDC_PANEL_BODY                  1001
#define IDC_CS_VIEWER                   1001
#define IDC_PANEL_RIGHT                 1002
#define IDC_CUSTOM_GRID                 1002
#define IDC_BTN_MODEL_CHANGE            1003
#define IDC_BUTTON_SEL_MAIN             1003
#define IDC_EDIT2                       1004
#define IDC_BUTTON_SEL_INPUT_ALIGN_1    1004
#define IDC_STATIC_PROGRAM_TITLE        1005
#define IDC_BUTTON_SEL_INPUT_ALIGN_2    1005
#define IDC_BTN_CREATE_MODEL            1006
#define IDC_BUTTON_SEL_PRECISION_ALIGN_1 1006
#define IDC_STATIC_PROGRAM_TITLE2       1006
#define IDC_STATIC_EQUIPMENT_TITLE      1006
#define IDC_EDIT3                       1007
#define IDC_STATIC_SEL_UNIT             1007
#define IDC_STATIC_NOW_TIME             1008
#define IDC_GROUP_BOX1                  1008
#define IDC_BUTTON_GETPARAM             1008
#define IDC_BTN_CREATE                  1009
#define IDC_BUTTON_SEL_PRECISION_ALIGN_2 1009
#define IDC_BUTTON_SEARCH               1009
#define IDC_BUTTON_SAVE_OFFSET          1009
#define IDC_EDIT4                       1010
#define IDC_BUTTON_SEL_PRECISION_ALIGN_3 1010
#define IDC_BUTTON_APPLY                1010
#define IDC_BUTTON_CLEAR_OFFSET         1010
#define IDC_BUTTON_SET_OFFSET           1010
#define IDC_BTN_LOGIN                   1010
#define IDC_EDIT_FIRST_PRINT            1010
#define IDC_STATIC_PROGRAM_VERSION      1011
#define IDC_BUTTON_SEL_PRECISION_ALIGN_4 1011
#define IDC_BUTTON_SET_OFFSET2          1011
#define IDC_BTN_DELETE                  1011
#define IDC_EDIT5                       1012
#define IDC_BUTTON_SEL_SAMPLING_ALIGN   1012
#define IDC_STATIC_CONNECT_SERVER       1013
#define IDC_BUTTON_SEL_INSPECTION       1013
#define IDC_EDIT6                       1014
#define IDC_CUSTOM_GRID2                1014
#define IDC_STATIC_CONNECT_CAM1         1015
#define IDC_GROUP_BOX2                  1015
#define IDC_EDIT7                       1016
#define IDC_BUTTON_SEL_LOAD_TRAY_GLASS_INSP 1016
#define IDC_STATIC_CONNECT_CAM6         1016
#define IDC_STATIC_CONNECT_CAM2         1017
#define IDC_BUTTON1                     1018
#define IDC_STATIC_CONNECT_CAM7         1018
#define IDC_BTN_AUTO_MAIN               1018
#define IDC_BTN_JOB_COUNT_MODIFY_OK     1018
#define IDC_BUTTON_CONNECT              1018
#define IDC_BUTTON_PROCESSING           1018
#define IDC_BTN_MARK_COPY               1018
#define IDC_BTN_MOVE_TO_CENTER_CALIPER  1018
#define IDC_BUTTON_CHANGE_IP            1018
#define IDC_BTN_MODEL                   1019
#define IDC_BTN_LIGHT_CONTROL_MODIFY    1019
#define IDC_BTN_MOVE_TO_CENTER_CALIPER2 1019
#define IDC_BTN_AUTO_MAIN2              1019
#define IDC_BTN_AUTO_TREND              1019
#define IDC_BUTTON_DISCONNECT           1019
#define IDC_BUTTON_PROCESSING_CLEAR     1019
#define IDC_BTN_SCALE_CALC_POPUP        1019
#define IDC_CS_GRID_INFO                1020
#define IDC_BTN_SIZE_ORIGINAL           1020
#define IDC_BTN_VIEWER_COUNT_MODIFY_OK  1020
#define IDC_BUTTON_REQDLAGENT           1020
#define IDC_BUTTON_PROCESSING_GET       1020
#define IDC_BTN_AUTO_CALIBRATION        1021
#define IDC_CS_GRID_RESULT              1021
#define IDC_BTN_CAMERA_COUNT_MODIFY_OK  1021
#define IDC_BUTTON_REPORTMANUAL_RST     1021
#define IDC_BUTTON_XML_CLEAR            1021
#define IDC_BTN_AUTO_START              1022
#define IDC_TAB_INFO                    1022
#define IDC_BTN_POS_MODIFY_OK           1022
#define IDC_BUTTON_REQUPDATE_ATT        1022
#define IDC_BTN_DELETE_MODEL            1023
#define IDC_EDIT_HISTORY                1023
#define IDC_BTN_JOB_CAMERA_COUNT_MODIFY_OK 1023
#define IDC_BUTTON_GETEQP_LIST          1023
#define IDC_BTN_SIZE_X1                 1024
#define IDC_BTN_JOB_DATA_MODIFY         1024
#define IDC_BTN_MACHINE_COUNT_MODIFY_OK 1024
#define IDC_BUTTON_MONITOR_LOG          1024
#define IDC_EDIT8                       1025
#define IDC_BTN_MAIN_COUNT_MODIFY_OK    1025
#define IDC_BUTTON_REQMODELDATA_COPY    1025
#define IDC_BTN_SEARCH_EDGE_COLOR1      1026
#define IDC_BTN_JOB_USE_LIGHT_MODIFY_OK 1026
#define IDC_BUTTON_REPORTLOGIC_RST      1026
#define IDC_BUTTON_LEFT_G               1026
#define IDC_STATIC_CONNECT_CAM3         1027
#define IDC_BUTTON_REPORT_ALLRST        1027
#define IDC_BUTTON_RIGTH_G              1027
#define IDC_BTN_CAMERA                  1028
#define IDC_BUTTON_SEL_STAGE_DISPLACEMENT_SENSOR_1 1028
#define IDC_STATIC_CONNECT_CAM8         1028
#define IDC_BUTTON_GETPOS_LIST          1028
#define IDC_BUTTON_ZERO                 1028
#define IDC_BTN_SIZE_X2                 1029
#define IDC_BUTTON_SEL_STAGE_DISPLACEMENT_SENSOR_2 1029
#define IDC_BUTTON_IMAGE_LOAD           1029
#define IDC_BUTTON_JUM                  1029
#define IDC_BTN_SEARCH_EDGE_COLOR2      1030
#define IDC_BUTTON_SEL_STAGE_DISPLACEMENT_SENSOR_3 1030
#define IDC_BUTTON_CLEAR_LOG            1030
#define IDC_BUTTON_EQURE                1030
#define IDC_BTN_INDIVIDUAL_CALIBRATION  1031
#define IDC_BUTTON_SEL_STAGE_DISPLACEMENT_SENSOR_4 1031
#define IDC_BUTTON_SET_DATA             1031
#define IDC_BUTTON_IMAGE_LOAD2          1031
#define IDC_BUTTON_COPY_CANCLE          1031
#define IDC_STATIC_CONNECT_CAM4         1032
#define IDC_BTN_ZOOM_IN                 1032
#define IDC_BUTTON_SEL_UV_MEASURE_1     1032
#define IDC_BTN_INDIVIDUAL_CALIBRATION2 1032
#define IDC_BTN_IMAGE_CALIBRATION       1032
#define IDC_BTN_MACHINE                 1033
#define IDC_BUTTON_SEL_UV_MEASURE_2     1033
#define IDC_STATIC_CONNECT_CAM9         1033
#define IDC_BTN_SIZE_X3                 1034
#define IDC_BUTTON_SEL_BCR_1            1034
#define IDC_EDIT9                       1035
#define IDC_BUTTON_SEL_BCR_2            1035
#define IDC_BTN_SEARCH_EDGE_COLOR3      1036
#define IDC_BUTTON_SEL_LOAD_TRAY_BCR    1036
#define IDC_BUTTON_P_AND_M              1036
#define IDC_BTN_INDIVIDUAL_ROTATE_CENTER 1037
#define IDC_STATIC_SEL_UNIT2            1037
#define IDC_BUTTON_ONE                  1037
#define IDB_PNG_TIME                    1038
#define IDC_BUTTON_SEL_SPARE            1038
#define IDC_BUTTON_TWO                  1038
#define IDC_STATIC_TITLE_MODEL          1039
#define IDC_STATIC_TITLE                1039
#define IDC_BUTTON_THREE                1039
#define IDC_BTN_INSPECTION              1040
#define IDC_BTN_INTERFACE               1040
#define IDC_EDIT_PROCESS                1040
#define IDC_BUTTON_PLUS                 1040
#define IDC_BTN_SIZE_X4                 1041
#define IDC_BTN_INSPECTION2             1041
#define IDC_BTN_INITIALIZATION          1041
#define IDC_BTN_SIMULATION              1041
#define IDC_BUTTON_FACTORYAL            1041
#define IDC_STATIC_CONNECT_CAM5         1042
#define IDC_BUTTON_SEL_SPARE2           1042
#define IDC_BTN_SIMULATION2             1042
#define IDC_BUTTON_FOUR                 1042
#define IDC_BTN_TREND                   1043
#define IDC_STATIC_CONNECT_PLC          1043
#define IDC_BUTTON_SEL_SPARE3           1043
#define IDC_BUTTON_FIVE                 1043
#define IDB_PNG_MAIN                    1044
#define IDC_STATIC_CONNECT_LIGHT1       1044
#define IDC_BUTTON_SIX                  1044
#define IDB_PNG_MANUAL                  1045
#define IDC_STATIC_CONNECT_LIGHT2       1045
#define IDB_PNG_ALARM                   1046
#define IDC_STATIC_CONNECT_TRIGGER1     1046
#define IDC_BUTTON_PAI                  1046
#define IDB_PNG_SYSTEM                  1047
#define IDC_STATIC_CONNECT_TRIGGER2     1047
#define IDC_BUTTON_SEVEN                1047
#define IDB_PNG_START                   1048
#define IDC_TAB_LIST                    1048
#define IDC_GRID_JOB_LIST               1048
#define IDC_BUTTON_EHIGH                1048
#define IDB_PNG_STOP                    1049
#define IDC_BUTTON_NINE                 1049
#define IDB_PNG_PISTOP                  1050
#define IDC_BUTTON_MULTI                1050
#define IDB_PNG_POSTOP                  1051
#define IDC_BTN_JOB_DATA_SAVE           1051
#define IDC_BUTTON_UP                   1051
#define IDB_PNG_PMSTOP                  1052
#define IDC_BUTTON_CE                   1052
#define IDB_PNG_IO                      1053
#define IDC_LIST_TRAIN                  1053
#define IDB_PNG_AREADY                  1054
#define IDC_BUTTON_BACK                 1054
#define IDC_BTN_MODEL_DATA_MODIFY       1055
#define IDC_BUTTON_NANUGI               1055
#define IDB_PNG_CONDITION               1056
#define IDC_BUTTON_SQURT                1056
#define IDB_PNG_EXIT                    1057
#define IDC_BUTTON_TEN_X                1057
#define IDC_BTN_CLOSE                   1058
#define IDC_BUTTON_LOG                  1058
#define IDB_PNG_BSTOP                   1059
#define IDC_BUTTON_EXP                  1059
#define IDB_PNG_MODEL                   1060
#define IDC_BUTTON_Mod                  1060
#define IDC_BTN_MODEL_DATA_SAVE         1061
#define IDC_BUTTON_ZEGOP                1061
#define IDB_PNG_ARUN                    1062
#define IDC_BUTTON_YZEGOP               1062
#define IDB_PNG_INTERFACE               1063
#define IDC_BUTTON_SIN                  1063
#define IDB_PNG_UDOOR                   1064
#define IDC_BUTTON_COS                  1064
#define IDB_PNG_JOG                     1065
#define IDC_BUTTON_TAN                  1065
#define IDC_BUTTON_COPYDATA_X           1066
#define IDC_BUTTON_COPY                 1066
#define IDB_PNG_OFFSET                  1067
#define IDC_BUTTON_PHASTE               1067
#define IDC_BUTTON_PASTE                1067
#define IDB_PNG_TLAMP                   1068
#define IDC_STATIC_SUB_MODEL            1069
#define IDB_PNG_UNSCRAP                 1070
#define IDB_PNG_SCRAP                   1071
#define IDB_PNG_NOM_DISPSPEED           1072
#define IDB_PNG_NOM_PLAN                1073
#define IDB_PNG_NOM_CYCLE               1074
#define IDB_PNG_NOM_EPCS                1075
#define IDB_PNG_NOM_EQPID               1076
#define IDB_PNG_NOM_HOST                1077
#define IDB_PNG_NOM_MARCO               1078
#define IDC_STATIC_PROCESS_HISTORY      1079
#define IDB_PNG_NOM_MARK                1080
#define IDC_STATIC_PROCESS_GLASSMOUNT   1081
#define IDC_LB_SELECTED_JOB_TITLE       1081
#define IDB_PNG_NOM_MELSEC              1082
#define IDC_STATIC_PROCESS_GLASSCHIP    1083
#define IDB_PNG_CHK_DISPSPEED           1084
#define IDC_STATIC_PROCESS_GLASSMOUNT_VALUE 1085
#define IDB_PNG_CHK_PLAN                1086
#define IDC_LB_SELECTED_JOB             1086
#define IDC_STATIC_PROCESS_GLASSCHIP2   1087
#define IDC_STATIC_PROCESS_GLASSCHIP_VALUE 1088
#define IDB_PNG_CHK_CYCLE               1089
#define IDC_LIST_MODEL                  1090
#define IDB_PNG_CHK_EPCS                1091
#define IDB_PNG_CHK_SEQPID              1092
#define IDC_STATIC_MODEL_NAME           1093
#define IDB_PNG_CHK_HOST                1094
#define IDB_PNG_CHK_MARCO               1095
#define IDB_PNG_CHK_MARK                1096
#define IDB_PNG_CHK_MELSEC              1097
#define IDB_PNG_CHK_WIPERCHANGE         1098
#define IDC_STATIC_GLASS_WIDTH          1099
#define IDB_PNG_NOM_WIPECHANGE          1100
#define IDC_STATIC_FRAME_WIDTH          1100
#define IDC_STATIC_TAB_WIDTH            1101
#define IDB_PNG_NOM_MAIN                1102
#define IDC_GRID_SYSTEM_OPTION          1102
#define IDC_STATIC_INCH_NAME            1103
#define IDC_GRID_PARAM2                 1103
#define IDB_PNG_CHK_MAIN                1104
#define IDC_STATIC_GLASS_HEIGHT         1105
#define IDB_PNG_BUTTON_GRAY             1106
#define IDC_STATIC_FRAME_HEIGHT         1106
#define IDC_STATIC_TAB_HEIGHT           1107
#define IDB_PNG_BUTTON_GREEN            1108
#define IDC_STATIC_MODEL_INFO           1109
#define IDB_PNG_BUTTON_PUPPLE           1110
#define IDC_STATIC_PANEL_ROW_COUNT      1111
#define IDB_PNG_BUTTON_RED              1112
#define IDC_STATIC_PANEL_COLUMN_COUNT   1113
#define IDB_PNG_BUTTON_NEXT             1114
#define IDC_STATIC_REVISION_LIMIT_X     1115
#define IDB_PNG_BUTTON_CIRCLE           1116
#define IDC_STATIC_INCLUDED_ANGLE       1116
#define IDC_STATIC_REVISION_LIMIT_Y     1117
#define IDB_PNG_BUTTON_BACK             1118
#define IDC_STATIC_INCLUDED_ANGLE_LIMIT 1118
#define IDC_STATIC_REVISION_LIMIT_T     1119
#define IDB_PNG_LOADING                 1120
#define IDC_STATIC_DUMMY_INCLUDED_ANGLE 1120
#define IDC_STATIC_GLASS_WIDTH_NAME     1121
#define IDC_STATIC_DUMMY_INCLUDED_ANGLE_LIMIT 1121
#define IDB_PNG_LETTER_M                1122
#define IDC_STATIC_MULTIPLEX_ROI        1122
#define IDC_STATIC_CALIB_COUNT_X        1123
#define IDC_STATIC_DISTANCE_INSP_LSL    1123
#define IDB_PNG_SETTING                 1124
#define IDC_STATIC_DISTANCE_INSP_USL    1124
#define IDC_STATIC_CALIB_COUNT_Y        1125
#define IDC_STATIC_EXIST_PANEL_GRAY     1125
#define IDC_LB_MODEL_ID_TITLE           1126
#define IDC_STATIC_EXIST_DUMMY_GRAY     1126
#define IDC_STATIC_CALIB_RANGE_X        1127
#define IDC_STATIC_DISTANCE_INSP_SPECY  1127
#define IDC_STATIC_DISTANCE_INSP_SPEC_X 1127
#define IDC_STATIC_DISTANCE_INSP_SUB_SPEC 1127
#define IDC_STATIC_GLASS_HEIGHT_NAME    1128
#define IDC_STATIC_DISTANCE_INSP_SPEC_X_MIXMAX 1128
#define IDC_STATIC_DISTANCE_INSP_SPEC_X_MINMAX 1128
#define IDC_STATIC_DISTANCE_INSP_SUB_SPEC_TOLERANCE 1128
#define IDC_LB_MODEL_ID                 1129
#define IDC_STATIC_DISTANCE_INSP_SPEC_Y 1129
#define IDC_STATIC_CALIB_RANGE_Y        1130
#define IDC_STATIC_DISTANCE_INSP_SPEC_Y_MINMAX 1130
#define IDC_LB_LOGIN                    1130
#define IDC_LB_PANEL_ID_TITLE           1131
#define IDC_STATIC_ELB_INSP_RANGE       1131
#define IDC_STATIC_ROTATE_RANGE         1132
#define IDC_STATIC_ELB_INSP_DISTANCE    1132
#define IDC_LB_PANEL_ID                 1133
#define IDC_STATIC_ROTATE_COUNT         1133
#define IDC_STATIC_ELB_TRACE_INTERVAL   1133
#define IDC_STATIC_ALIGN_SPEC           1134
#define IDC_CS_VIEWER1                  1135
#define IDC_STATIC_ELB_INSP_HI_THRESH   1135
#define IDC_STATIC_ALIGN_SPEC_MINMAX    1136
#define IDC_CS_VIEWER2                  1137
#define IDC_STATIC_ELB_INSP_LOW_TH      1137
#define IDC_CS_VIEWER_CAMERA            1138
#define IDC_STATIC_ELB_INSP_HOLE_C1     1138
#define IDC_EDIT_GLASS_WIDTH            1139
#define IDC_STATIC_ELB_INSP_HOLE_C2     1139
#define IDC_CS_VIEWER3                  1140
#define IDC_EDIT_FRAME_WIDTH            1140
#define IDC_STATIC_ELB_INSP_HOLE_C3     1140
#define IDC_BTN_MACHINE_CLOSE           1141
#define IDC_STATIC_ELB_INSP_DUST        1141
#define IDC_STATIC_MARK_PITCH_X         1142
#define IDC_CHECK_EDGE_VIEW             1142
#define IDC_STATIC_DISTANCE_INSP_HOLE_METAL 1142
#define IDC_CS_VIEWER4                  1143
#define IDC_STATIC_INSP_JUDGE_SPEC      1143
#define IDC_BTN_CAMERA_CLOSE            1144
#define IDC_STATIC_INSP_JUDGE_SPEC_TORR 1144
#define IDC_EDIT_GLASS_HEIGHT           1145
#define IDC_STATIC_INSP_PARA_ITEM1      1145
#define IDC_BTN_MODEL_CLOSE             1146
#define IDC_EDIT_FRAME_HEIGHT           1146
#define IDC_STATIC_INSP_PARA_ITEM2      1146
#define IDC_EDIT_TAB_WIDTH              1147
#define IDC_STATIC_DASH                 1147
#define IDC_LB_PANEL_ID2                1148
#define IDC_STATIC_TRACE_IMAGE_THRESH   1148
#define IDC_LB_PANEL_JUDGE              1149
#define IDC_STATIC_FIND_EDGE_THRESH     1149
#define IDC_BTN_OK                      1150
#define IDC_STATIC_INSP_PARA_ITEM3      1150
#define IDC_STATIC_DIFF_INSP_PARA_ITEM1 1150
#define IDC_EDIT_TAB_HEIGHT             1151
#define IDC_STATIC_INSP_PARA_ITEM4      1151
#define IDC_STATIC_DIFF_INSP_PARA_ITEM2 1151
#define IDC_BTN_CANCEL                  1152
#define IDC_STATIC_DASH2                1152
#define IDC_BTN_SIZE_FIT                1153
#define IDC_STATIC_ELB_INSP_MINSIZE     1153
#define IDC_EDIT_PANEL_ROW_COUNT        1154
#define IDC_BTN_CAMERA_LIVE             1155
#define IDC_EDIT_PANEL_COLUMN_COUNT     1156
#define IDC_CAMERA_STOP                 1157
#define IDC_BTN_CAMERA_STOP             1158
#define IDC_EDIT_REVISION_LIMIT_X       1159
#define IDC_BTN_IMAGE_SAVE              1160
#define IDC_BTN_CAMERA_STOP3            1161
#define IDC_EDIT_REVISION_LIMIT_Y       1161
#define IDC_BTN_CAMERA_SIMULATION       1161
#define IDC_BTN_IMAGE_OPEN              1162
#define IDC_EDIT_REVISION_LIMIT_T       1163
#define IDC_BTN_LIVE_SIMULATION         1163
#define IDC_BTN_CAMERA_INSPECTION       1163
#define IDC_EDIT_INCLUDED_ANGLE         1164
#define IDC_LB_SELECT_CAMERA            1164
#define IDC_STATIC_INSPROI_OFFSET       1165
#define IDC_BTN_CAMERA_INSPECTION2      1165
#define IDC_BTN_DELETE_LIST             1165
#define IDC_BTN_CAMERA_MAKE__MASKING    1165
#define IDC_CB_SELECT_CAMERA            1166
#define IDC_EDIT_INCLUDED_ANGLE_LIMIT   1166
#define IDC_BTN_REVERSE_SELECT          1166
#define IDC_EDIT_CALIB_COUNT_X          1167
#define IDC_BTN_CAMERA_MAKE__MASKING2   1167
#define IDC_BTN_CAMERA_SHOW_GOLD_TRACE  1167
#define IDC_CB_SELECT_POS               1167
#define IDC_BTN_CAMERA_MAKE_METAL_DATA  1167
#define IDC_EDIT_DUMMY_INCLUDED_ANGLE   1168
#define IDC_BTN_CAMERA_MAKE_METAL_DATA2 1168
#define IDC_BTN_CAMERA_MAKE_TRACE_DATA  1168
#define IDC_EDIT_CALIB_COUNT_Y          1169
#define IDC_BTN_CAMERA_SINGLE_GRAB      1170
#define IDC_EDIT_DUMMY_INCLUDED_ANGLE_LIMIT 1170
#define IDC_EDIT_DISTANCE_INSP_LSL      1171
#define IDC_LB_PATTERN_INDEX            1171
#define IDC_EDIT_CALIB_RANGE_X          1172
#define IDC_EDIT_DISTANCE_INSP_USL      1172
#define IDC_EDIT_EXIST_PANEL_GRAY       1173
#define IDC_EDIT_EXIST_PANEL_GRAY2      1174
#define IDC_EDIT_EXIST_DUMMY_GRAY       1174
#define IDC_CB_PATTERN_INDEX            1174
#define IDC_STATIC_MESSAGE              1175
#define IDC_EDIT_DISTANCE_INSP_SPEC2    1175
#define IDC_EDIT_DISTANCE_INSP_SPECY    1175
#define IDC_EDIT_DISTANCE_INSP_SUB_SPEC 1175
#define IDC_EDIT_CALIB_RANGE_Y          1176
#define IDC_EDIT_DISTANCE_INSP_SUB_SPEC_TOLERANCE 1176
#define IDC_BTN_CALIPER_DIRECTION_SWAP  1177
#define IDC_EDIT_DISTANCE_INSP_SPEC_Y   1177
#define IDC_EDIT_DISTANCE_INSP_SPEC_Y_MIMAX 1178
#define IDC_EDIT_DISTANCE_INSP_SPEC_Y_MINMAX 1178
#define IDC_LB_MATCHING_RATE            1178
#define IDC_BTN_MESSAGE_OK              1179
#define IDC_EDIT_ELB_INSP_RANGE         1179
#define IDC_EDIT_ELB_INSP_RANGE_X       1179
#define IDC_LB_ROI_X                    1179
#define IDC_EDIT_ROTATE_RANGE           1180
#define IDC_EDIT_EXIST_DUMMY_GRAY2      1180
#define IDC_EDIT_ELB_INSP_LENGTH        1180
#define IDC_LB_ROI_Y                    1180
#define IDC_EDIT_ROTATE_RANGE2          1181
#define IDC_EDIT_ROTATE_COUNT           1181
#define IDC_EDIT_ELB_INSP_RANGE2        1181
#define IDC_EDIT_ELB_INSP_RANGE_Y       1181
#define IDC_EDIT_ELB_INSP_LENGTH2       1182
#define IDC_EDIT_ELB_TRACE_INTERVAL     1182
#define IDC_EDIT_ROTATE_START           1182
#define IDC_EDIT_ROTATE_STARTPOS        1182
#define IDC_EDIT_MATCHING_RATE          1182
#define IDC_EDIT_ELB_INSP_LOW_THRESH    1183
#define IDC_EDIT_ROTATE_ENDPOS          1183
#define IDC_BTN_PATTERN_REGIST          1183
#define IDC_EDIT_ALIGN_SPEC             1184
#define IDC_EDIT_ROI_X                  1184
#define IDC_EDIT_ELB_INSP_HI_THRESH     1185
#define IDC_BTN_PATTERN_SEARCH          1185
#define IDC_EDIT_ALIGN_SPEC_MINMAX      1186
#define IDC_EDIT_ROI_X2                 1186
#define IDC_EDIT_ROI_Y                  1186
#define IDC_EDIT_ELB_INSP_HOLE_C1       1187
#define IDC_BTN_PATTERN_VIEW            1187
#define IDC_BTN_MESSAGE_CANCEL          1188
#define IDC_EDIT_ELB_INSP_HOLE_C2       1188
#define IDC_BTN_PATTERN_TEMP            1188
#define IDC_EDIT_MARK_PITCH_X           1189
#define IDC_EDIT_ELB_INSP_HOLE_C3       1189
#define IDC_BTN_PATTERN_CLEAR           1189
#define IDC_EDIT_ELB_INSP_HOLE_C4       1190
#define IDC_EDIT_ELB_INSP_DUST          1190
#define IDC_BTN_SET_ROI                 1190
#define IDC_LB_TEXT1                    1191
#define IDC_EDIT_DISTANCE_INSP_SUB_SPEC2 1191
#define IDC_EDIT_DISTANCE_INSP__HOLE_METAL 1191
#define IDC_BTN_PATTERN_ALIGN_REF       1191
#define IDC_EDIT_ALIGN_LEFT_RIGHT_DIFF_SPEC 1192
#define IDC_EDIT_INSP_JUDGE_SPEC        1192
#define IDC_BTN_NOZZLE_INSP             1192
#define IDC_BTN_DRAW_ROI                1193
#define IDC_EDIT_INSP_JUDGE_SPEC_TORR   1193
#define IDC_BTN_DRAW_AREA               1194
#define IDC_EDIT_INSP_PARA_ITEM1        1194
#define IDC_LB_TEXT2                    1195
#define IDC_EDIT_INSP_PARA_ITEM2        1195
#define IDC_STATIC_THETA_CALIB_COUNT    1196
#define IDC_EDIT_TRACE_IMAGE_THRESH     1196
#define IDC_LB_CAMERA_VIEW_TITLE        1197
#define IDC_EDIT_FIND_LINE_THRESH       1197
#define IDC_EDIT_FIND_EDGE_THRESH       1197
#define IDC_EDIT_THETA_CALIB_COUNT      1198
#define IDC_EDIT_INSP_PARA_ITEM3        1198
#define IDC_EDIT_DIFF_INSP_PARA_ITEM1   1198
#define IDC_BTN_SET_ROI2                1199
#define IDC_EDIT_INSP_PARA_ITEM4        1199
#define IDC_EDIT_DIFF_INSP_PARA_ITEM2   1199
#define IDC_BTN_INSP_SET_PARAM          1200
#define IDC_BTN_DRAW_AREA2              1201
#define IDC_EDIT_ELB_INSP_DUST2         1201
#define IDC_EDIT_ELB_INSP_MINSIZE       1201
#define IDC_BTN_REGIST_BASE_IMAGE       1202
#define IDC_LB_SELECT_DRAW_SHAPE        1203
#define IDC_LB_IMAGE_INFO               1204
#define IDC_CB_SELECT_DRAW_SHAPE        1206
#define IDC_EDIT_INSP_ROIOFFSET         1207
#define IDC_LB_IMAGE_INFO2              1209
#define IDC_EDIT_INSP_FILTER_CONTRAST   1211
#define IDC_EDIT_LIGHT_SETTING          1212
#define IDC_EDIT_LIGHT_SETTING3         1213
#define IDC_EDIT_EXPOSURE_SETTING       1213
#define IDC_STATIC_INSPFILTER_CONTRAST  1215
#define IDC_EDIT_LIGHT_SETTING2         1216
#define IDC_EDIT_LIGHT_SETTING_SECOND   1217
#define IDC_LB_IMAGE_INFO3              1218
#define IDC_EDIT_MATCHING_RATE4         1219
#define IDC_EDIT_INSP_FILTER_SIZE       1222
#define IDC_STATIC_SELECT_LINE          1222
#define IDC_STATIC_COPY_CAM             1223
#define IDC_LB_SELECT_PROCESS2          1223
#define IDC_BTN_SET_SAVE                1224
#define IDC_STATIC_COPY_POS             1224
#define IDC_STATIC_COPY_LINE            1225
#define IDC_CS_MARK_VIEW                1226
#define IDC_STATIC_COPY_JOB             1226
#define IDC_STATIC_INSPFILTER_SIZE      1227
#define IDC_BTN_DRAW_AREA3              1228
#define IDC_COMBO_SELECT_LINE           1229
#define IDC_EDIT_INSP_NOZZLE_CIRCULARITY 1230
#define IDC_STATIC_INSPNOZZLE_CIRCULARITY 1231
#define IDC_BTN_PATTERN_SAVE            1232
#define IDC_EDIT_INSP_FILTER_SIZE2      1233
#define IDC_EDIT_INSP_ROTATE_ANGLE      1234
#define IDC_BTN_FOCUS_MEASURE           1235
#define IDC_STATIC_INSP_ROTATE_ANGLE    1236
#define IDC_BTN_FIXTURE_POS             1236
#define IDC_LB_FOCUS_ENERGY_TITLE       1237
#define IDC_COMBO_EDGE_POLARITY         1237
#define IDC_TAB                         1237
#define IDC_STATIC_ROTATE_RANGE2        1238
#define IDC_LB_NUM_LEVELS               1238
#define IDC_COMBO_EDGE_POLARITY2        1238
#define IDC_COMBO_SEARCH_DIR            1238
#define IDC_LB_REFERENCE_POS_X_TITLE    1238
#define IDC_STATIC_THETA_OFFSET         1239
#define IDC_STATIC_REVISION_OFFSET_T    1239
#define IDC_LB_ANGLE_START              1239
#define IDC_LB_REFERENCE_POS_Y_TITLE    1239
#define IDC_LB_FOCUS_ENERGY             1240
#define IDC_STATIC_REVISION_OFFSET_Y    1240
#define IDC_LB_ANGLE_EXTENT             1240
#define IDC_EDIT_MARK_PITCH_X2          1241
#define IDC_STATIC_REVISION_OFFSET_X    1241
#define IDC_LIST_CALIPER                1241
#define IDC_LB_ANGLE_STEP               1241
#define IDC_LB_REFERENCE_POS_X          1241
#define IDC_LB_REF_POS_Y                1242
#define IDC_EDIT_MARK_PITCH_Y           1242
#define IDC_STATIC_EDGE_POLARITY        1242
#define IDC_LB_OPTIMIAZTION             1242
#define IDC_LB_REFERENCE_POS_Y          1242
#define IDC_BUTTON2                     1243
#define _                               1243
#define IDC_BTN_AUTO_PLC_INTERFACE      1243
#define IDC_LB_METRIC                   1243
#define IDC_BTN_INI_SETTING_SAVE        1243
#define IDC_STATIC_SEARCH_DIR           1243
#define IDC_BTN_CALC                    1243
#define IDC_BTN_SHOW_CALIPER            1243
#define IDC_BTN_ROTATE_CENTER           1244
#define IDC_LB_CONTRAST                 1244
#define IDC_BTN_INI_EXIT                1244
#define IDC_BTN_SAVE                    1244
#define IDC_BTN_AUTO_PLC_INTERFACE2     1244
#define IDC_BTN_AUTO_RESULT_LIST        1244
#define IDC_LB_REFERENCE_POS_T_TITLE    1244
#define IDC_STATIC_SEARCH_TYPE          1245
#define IDC_LB_MIN_CONTRAST             1245
#define IDC_BTN_INI_CAM_MATCHIG         1245
#define IDC_LB_REFERENCE_POS_T          1245
#define IDC_BTN_AUTO_STOP               1246
#define IDC_CB_SELECT_OPTIMIZE          1246
#define IDC_BTN_FOCUS_MEASURE2          1247
#define IDC_CB_SELECT_METRIC            1247
#define IDC_BTN_MANUAL_INSP             1248
#define IDC_COMBO_SEARCH_TYPE           1248
#define IDC_EDIT_CONTRAST               1248
#define IDC_LB_FIXTURE_POS_X_TITLE      1248
#define IDC_BTN_SIZE_X5                 1249
#define IDC_CALIPER_TAB                 1249
#define IDC_EDIT_CONTRAST2              1249
#define IDC_COMBO_COPY_CAM              1249
#define IDC_LB_FIXTURE_POS_Y_TITLE      1249
#define IDC_BTN_PATTERN_DELETE          1250
#define IDC_EDIT_NUMLEVEL               1250
#define IDC_BTN_SIZE_X6                 1250
#define IDC_COMBO_COPY_POS              1250
#define IDC_BTN_SEARCH_DIRECTION1       1251
#define IDC_EDIT_S_ANGLE                1251
#define IDC_COMBO_COPY_LINE             1251
#define IDC_LB_FIXTURE_POS_X            1251
#define IDC_EDIT_MACHINE_PROCESS_HISTORY 1252
#define IDC_PIC_CALIPER                 1252
#define IDC_EDIT_E_ANGLE                1252
#define IDC_COMBO_COPY_JOB              1252
#define IDC_LB_REFERENCE_POS_Y2         1252
#define IDC_LB_FIXTURE_POS_Y            1252
#define IDC_BTN_EXIST_CHECK             1253
#define IDC_EDIT_STEP_ANGLE             1253
#define IDC_LB_FIXTURE_POS_T_TITLE      1253
#define IDC_LB_LIGHT_SETTING            1254
#define IDC_LB_LIGHT_CHANNEL            1254
#define IDC_LB_METHOD                   1254
#define IDC_LB_LIGHT_SETTING2           1255
#define IDC_LB_LIGHT_INDEX              1255
#define IDC_BTN_SEARCH_DIRECTION2       1255
#define IDC_STATIC_NUM_OF_CALIPER       1255
#define IDC_CB_SELECT_METHOD            1255
#define IDC_CS_MACHINE_VIEWER1          1256
#define IDC_EDIT_NUM_OF_CALIPER         1256
#define IDC_LB_NUM_MATCH                1256
#define IDC_LB_EXPOSURETIME             1256
#define IDC_LIST_INSPECTION             1257
#define IDC_CS_MACHINE_VIEWER5          1257
#define IDC_STATIC_PROJECTION_LENGTH    1257
#define IDC_EDIT_MINSCORE               1257
#define IDC_LB_FIXTURE_POS_T            1257
#define IDC_LB_LIGHT_SETTING_SECOND     1258
#define IDC_EDIT_PROJECTION_LENGTH      1258
#define IDC_LB_SUBPIXEL                 1258
#define IDC_LIST_INSPECTION2            1258
#define IDC_BTN_PATTERN_DELETE2         1258
#define IDC_BTN_PATTERN_COPY            1258
#define IDC_BTN_SEARCH_DIRECTION3       1259
#define IDC_STATIC_SEARCH_LENGTH        1259
#define IDC_CB_SELECT_SUBPIXEL          1259
#define IDC_LIST_INSPECTION3            1259
#define IDC_CS_MACHINE_VIEWER2          1260
#define IDC_EDIT_SEARCH_LENGTH          1260
#define IDC_LB_GREEDNIESS               1260
#define IDC_LIST_INSPECTION4            1260
#define IDC_STATIC_MARK_PITCH_Y         1261
#define IDC_BTN_CALIPER_FIND            1261
#define IDC_SLIDER_LOW                  1261
#define IDC_LIST_INSPECTION5            1261
#define IDC_LB_GREEDNIESS2              1261
#define IDC_LB_SCALE                    1261
#define IDC_CS_MACHINE_VIEWER3          1262
#define IDC_STATIC_THRESHOLD            1262
#define IDC_SLIDER_HIGH                 1262
#define IDC_LIST_INSPECTION6            1262
#define IDC_EDIT_INSP_ROIOFFSET2        1263
#define IDC_EDIT_THRESHOLD              1263
#define IDC_LIST_INSPECTION7            1263
#define IDC_CS_MACHINE_VIEWER4          1264
#define IDC_BTN_CALIPER_INFO_SAVE       1264
#define IDC_LIST_INSPECTION8            1264
#define IDC_STATIC_INSPROI_OFFSET2      1265
#define IDC_RADIO_DARK_TO_LIGHT         1265
#define IDC_LB_MACHINE_VIEW_TITLE       1266
#define IDC_RADIO_LIGHT_TO_DARK         1266
#define IDC_EDIT_INSP_ROIOFFSET3        1267
#define IDC_RADIO_PEAK                  1267
#define IDC_LB_MACHINE_VIEW_CALIB_DATE  1267
#define IDC_LB_SELECT_MACHINE_CAMERA_TITLE 1268
#define IDC_RADIO_CALIPER_FIRST         1268
#define IDC_LB_MACHINE_VIEW_ROTATE_DATE 1268
#define IDC_STATIC_INSPROI_OFFSET3      1269
#define IDC_RADIO_CALIPER_LAST          1269
#define IDC_LB_CHESS_BOARD_TITLE        1269
#define IDC_LB_CAMERA_RESOLUTION_X_TITLE 1270
#define IDC_RADIO_BOTH                  1270
#define IDC_EDIT_CREATE_GLASS_WIDTH     1271
#define IDC_STATIC_HALF_FILTER          1271
#define IDC_LB_CHESS_X_TITLE            1271
#define IDC_EDIT_INSP_ROIOFFSET4        1272
#define IDC_EDIT_HALF_FILTER_SIZE       1272
#define IDC_LB_ROTATE_X_TITLE           1273
#define IDC_BTN_CALIPER_COPY            1273
#define IDC_EDIT_CREATE_GLASS_HEIGHT    1274
#define IDC_BTN_CALIPER_INFO_CLOSE      1274
#define IDC_STATIC_INSPROI_OFFSET4      1275
#define IDC_LB_ROTATE_Y_TITLE           1276
#define IDC_EDIT_CREATE_MODEL           1277
#define IDC_STATIC_CALIPER_SEARCH_TYPE  1277
#define IDC_EDIT_INSP_NOZZLE_CIRCULARITY2 1278
#define IDC_COMBO_CALIPER_SEARCH_TYPE   1278
#define IDC_EDIT_INSP_GRAB_SECOND       1279
#define IDC_CHECK_CIRCLE_FITTING        1279
#define IDC_CB_SELECT_MACHINE_CAMERA    1280
#define IDC_STATIC_NUM_OF_IGNORE        1280
#define IDC_EDIT_CREATE_INCH            1281
#define IDC_EDIT_NUM_OF_IGNORE          1281
#define IDC_STATIC_GRAB_SECOND          1282
#define IDC_STATIC_FITTING_METHOD       1282
#define IDC_LB_CAMERA_RESOLUTION        1283
#define IDC_COMBO_FITTING_METHOD        1283
#define IDC_LB_CAMERA_RESOLUTION_X      1284
#define IDC_EDIT_ORG_START_X            1284
#define IDC_STATIC_USE_4POINT_ALIGN     1285
#define IDC_EDIT_ORG_START_Y            1285
#define IDC_LB_ROTATE_X                 1286
#define IDC_STATIC_USE_CRACK_INSP       1286
#define IDC_EDIT_ORG_END_X              1286
#define IDC_STATIC_USING_1CAM           1287
#define IDC_EDIT_ORG_END_Y              1287
#define IDC_LB_ROTaFATE_X               1288
#define IDC_STATIC_USE_INCLUDED_ANGLE   1288
#define IDC_EDIT_START_X                1288
#define IDC_LB_ROTATE_Y                 1289
#define IDC_STATIC_USE_DUMMY_CORNER_INSP 1289
#define IDC_EDIT_START_Y                1289
#define IDC_STATIC_ENABLE_2SHOT_ALIGN   1290
#define IDC_EDIT_END_X                  1290
#define IDC_LB_CAMERA_RESOLUTION_Y_TITLE 1291
#define IDC_STATIC_DUMMY_CORNER_INSP_CAM 1291
#define IDC_EDIT_END_Y                  1291
#define IDC_LB_MOVE_X                   1292
#define IDC_STATIC_USE_BOX_INSP         1292
#define IDC_STATIC_USE_BOX_INSPECTION   1292
#define IDC_EDIT_FIXTURE_X              1292
#define IDC_EDIT_MOVE_X                 1293
#define IDC_STATIC_DUMMY_CORNER_FILTER  1293
#define IDC_EDIT_FIXTURE_Y              1293
#define IDC_LB_MOVE_Y                   1294
#define IDC_STATIC_USE_BOX_INSPECTION2  1294
#define IDC_STATIC_USE_DUMMY_SEPAR_INSPECTION 1294
#define IDC_EDIT_FIXTURE_T              1294
#define IDC_LB_MOVE_T                   1295
#define IDC_RADIO_POS                   1295
#define IDC_STATIC_USE_FIXTURE_MARK     1295
#define IDC_EDIT_MOVE_Y                 1296
#define IDC_STATIC_FIXTURE_X            1296
#define IDC_STATIC_USE_POST_INSPECTION  1296
#define IDC_EDIT_MOVE_T                 1297
#define IDC_STATIC_FIXTURE_Y            1297
#define IDC_STATIC_USE_DUST_INSPECTION  1297
#define IDC_LB_DAILY_TITLE              1297
#define IDC_BTN_MOVE                    1298
#define IDC_STATIC_USE_REALTIME_TRACE   1298
#define IDC_EDIT1                       1299
#define IDC_STATIC_FIXTURE_T            1299
#define IDC_LB_CHESS_Y_TITLE            1299
#define IDC_STATIC_USE_CYCLE_TRACE      1299
#define IDC_LB_DAILY_TITLE2             1299
#define IDC_EDIT_PROCESS_HISTORY        1300
#define IDC_LB_CHESS_SQUARE_TITLE       1300
#define IDC_STATIC_USE_REVERSE_ORDER    1300
#define IDC_EDIT_DLTIMEOUT              1300
#define IDC_EDIT_SUBNET_MASK            1300
#define IDC_LB_CAMERA_RESOLUTION2       1301
#define IDC_STATIC_SELECT_MTON_DISTANCE_ALGORITHM 1301
#define IDC_EDIT_MCTIMEOUT              1301
#define IDC_LB_CALIB_PIXEL              1301
#define IDC_EDIT_GATEWAY                1301
#define IDC_LB_CAMERA_RESOLUTION_Y      1302
#define IDC_STATIC_USE_AUTOSAVE_AVI     1302
#define IDC_EDIT_ATTTIMEOUT             1302
#define IDC_EDIT_REMOVE_NOISE_SIZE1     1303
#define IDC_EDIT_CALIB_PIXEL            1303
#define IDC_EDIT_REMOVE_NOISE_SIZE2     1304
#define IDC_LB_CALIB_ROBOT              1304
#define IDC_BTN_MOV                     1305
#define IDC_STATIC_USE_BM_BASE          1305
#define IDC_LB_CALIB_SUB                1305
#define IDC_BTN_RECALC_ROTATECENTER     1306
#define IDC_STATIC_USE_INPUT_INSPECTION 1306
#define IDC_EDIT_CALIB_ROBOT            1306
#define IDC_LB_SELECT_POSITION          1307
#define IDC_STATIC_USE_REFENCE_MARK     1307
#define IDC_STATIC_USE_REFERENCE_MARK   1307
#define IDC_EDIT_CALIB_SUB              1307
#define IDC_EDIT_REMOVE_NOISE_SIZE3     1308
#define IDC_STATIC_USE_GRAB_DELAY       1308
#define IDC_LB_SELECT_MACHINE_CAMERA_TITLE2 1309
#define IDC_EDIT_CAMERA_RESOLUTION      1309
#define IDC_LB_SELECT_MACHINE_POSITION_TITLE 1310
#define IDC_CB_SELECT_POSITION          1311
#define IDC_LB_SELECT_MACHINE_ORGINPOS_TITLE 1311
#define IDC_EDIT_REMOVE_NOISE_SIZE4     1312
#define IDC_LB_SELECT_MACHINE_PATTERN_INDEX 1312
#define IDC_CB_SELECT_MACHINE_POSITION  1313
#define IDC_PANEL_BOTTOM                1314
#define IDC_CB_SELECT_MACHINE_ORG_POSITION 1314
#define IDC_STATIC_USE_METAL_TRACE_FIRST 1315
#define IDC_CB_SELECT_MACHINE_PATTERN_INDEX 1315
#define IDC_STATIC_SELECT_CAMERA        1316
#define IDC_CB_SELECT_MACHINE_CAMERA2   1317
#define IDC_CB_SELECT_MACHINE_CALIBNUM  1318
#define IDC_BUTTON3                     1319
#define IDC_BTN_EXIT                    1320
#define IDC_STATIC_USE_METAL_TRACE      1321
#define IDC_BUTTON_TEST                 1322
#define IDC_BTN_RECALC_ROTATE_CENTER    1323
#define IDC_BTN_MANUAL_CALIBRATION      1324
#define IDC_BTN_CALC_LIMIT_OFFSET       1325
#define IDC_STATIC_SELECT_MINI_VIEWER_TITLE1 1326
#define IDC_STATIC_SELECT_MINI_VIEWER_TITLE2 1327
#define IDC_COMBO1                      1328
#define IDC_CB_MODEL_SELECT_POS         1328
#define IDC_CB_SELECT_VIEWER            1328
#define IDC_COMBO_LEVEL                 1328
#define IDC_COMBO_JOB_LIST              1328
#define IDC_COMBO_POSNAME               1328
#define IDC_CB_SRC_JOB                  1328
#define IDC_COMBO_ADAPT_LIST            1328
#define IDC_CB_MARK_FIND_METHOD         1329
#define IDC_COMBO_EQPNAME               1329
#define IDC_CB_SRC_CAM                  1329
#define IDC_COMBO_ADAPT_LIST2           1329
#define IDC_COMBO_ADAPT_NAME            1329
#define IDC_BTN_ENABLE_ALIGN_MEASURE    1330
#define IDC_CB_SELECT_CAM               1330
#define IDC_CB_MODEL_SELECT_CAM         1330
#define IDC_CB_ETC_NAME                 1330
#define IDC_CB_SRC_POS                  1330
#define IDC_LB_SELECT_SENSOR            1331
#define IDC_CB_NUM_OF_USING_CAMERA      1331
#define IDC_CB_SRC_INDEX                1331
#define IDC_LB_SELECT_CHIP              1332
#define IDC_CB_ETC_TYPE                 1332
#define IDC_CB_DST_JOB                  1332
#define IDC_BTN_INPUT_COMPLETE          1333
#define IDC_CB_SELECT_LIGHT_CAMERA      1333
#define IDC_CB_DST_CAM                  1333
#define IDC_CB_MARK_FIND_METHOD2        1334
#define IDC_CB_NUM_OF_USING_CAMERA3     1334
#define IDC_CB_NUM_OF_USING_CAMERA2     1334
#define IDC_CB_DST_POS                  1334
#define IDC_BTN_ENABLE_ALIGN_MEASURE_SPEC_OUT_JUDGE 1335
#define IDC_CB_NUM_OF_USING_CAMERA4     1335
#define IDC_CB_DST_INDEX                1335
#define IDC_CB_SELECT_SENSOR            1336
#define IDC_CB_SELECT_JOB               1336
#define IDC_CB_SELECT_CHIP              1337
#define IDC_BTN_MANUAL_INPUT_NG         1338
#define IDC_CB_SELECT_CHIP2             1338
#define IDC_CB_MARK_FIND_METHOD3        1339
#define IDC_CB_CHIP_RANSAC_DIRECTION    1340
#define IDC_BTN_ENABLE_ALIGN_LEFT_RIGHT_DIFF_JUDGE 1341
#define IDC_LB_AVG_GRAY_LIMIT           1342
#define IDC_STATIC_BTN_LEFT             1343
#define IDC_CB_EDGE_POLARITY0           1344
#define IDC_LB_MODEL_VIEW_TITLE         1345
#define IDC_EDIT_AVG_GRAY_LIMIT         1346
#define IDC_STATIC_BTN_RIGHT            1347
#define IDC_BTN_SELECT_CAM1             1348
#define IDC_STATIC_PICTURE              1349
#define IDC_BTN_SELECT_CAM3             1349
#define IDC_BTN_SELECT_POSITION3        1349
#define IDC_STATIC_BTN_TOP              1350
#define IDC_BTN_SELECT_CAM2             1351
#define IDC_CHK_ENABLE_ALIGN_MEASURE    1352
#define IDC_BTN_SELECT_CAM4             1352
#define IDC_BTN_SELECT_POSITION4        1352
#define IDC_STATIC_BTN_BOTTOM           1353
#define IDC_STATIC_BTN_RIGHT2           1354
#define IDC_CHK_ENABLE_ALIGN_MEASURE_SPEC_OUT_JUDGE 1355
#define IDC_CHECK1                      1356
#define IDC_CHK_SAVE_RAW_IMAGE          1356
#define IDC_CHK_MANUAL_PREALIGN         1356
#define IDC_CHECK_COPY                  1357
#define IDC_CHK_SAVE_RESLT_IMAGE        1357
#define IDC_CHECK2                      1357
#define IDC_CHECK_WHOLE_SET_ROI         1358
#define IDC_CHECK_CALC_WHOLE_ROI        1359
#define IDC_STATIC_BTN_TOP2             1360
#define IDC_CHK_ENABLE_ALIGN_LEFT_RIGHT_DIFF_JUDGE 1361
#define IDC_STATIC_BTN_BOTTOM2          1363
#define IDC_CHK_ENABLE_ALIGN_LEFT_RIGHT_DIFF_JUDGE2 1365
#define IDC_CHK_BLACK_PANEL_CHECK       1366
#define IDC_STATIC_MARK_FIND_METHOD     1367
#define IDC_STATIC_REMOVE_NOISE_SIZE1   1369
#define IDC_STATIC_REMOVE_NOISE_SIZE2   1371
#define IDC_STATIC_SOBEL_THRESHOLD1     1372
#define IDC_STATIC_SOBEL_THRESHOLD2     1373
#define IDC_EDIT_SOBEL_THRESHOLD1       1374
#define IDC_EDIT_SOBEL_THRESHOLD2       1375
#define IDC_COMBO_ALIGNMENT_TARGET      1376
#define IDC_STATIC_SEARCH_AREA_L1       1377
#define IDC_COMBO_THETA_REFERENCE       1378
#define IDC_COMBO_ALIGNMENT_TARGET3     1378
#define IDC_COMBO_LCHECK_REFERENCE      1378
#define IDC_STATIC_SEARCH_AREA_L2       1379
#define IDC_STATIC_SEARCH_AREA_R1       1380
#define IDC_STATIC_SEARCH_AREA_R2       1381
#define IDC_EDIT_SEARCH_AREA_LEFT1      1382
#define IDC_EDIT_SEARCH_AREA_LEFT2      1383
#define IDC_EDIT_SEARCH_AREA_RIGHT1     1384
#define IDC_EDIT_SEARCH_AREA_RIGHT2     1385
#define IDC_LB_JUDGE_CONDITION          1386
#define IDC_STATIC_PROJECTION_AREA_L1   1386
#define IDC_CB_JUDGE_CONDITION          1387
#define IDC_STATIC_PROJECTION_AREA_L2   1387
#define IDC_EDIT_SOBEL_THRESHOLD3       1388
#define IDC_COMBO_ALIGNMENT_TARGET2     1389
#define IDC_STATIC_SEARCH_AREA_R3       1389
#define IDC_STATIC_PROJECTION_AREA_R1   1389
#define IDC_COMBO_ALIGNMENT_TYPE        1390
#define IDC_BTN_SET_ROI_EXIST           1391
#define IDC_STATIC_PROJECTION_AREA_R2   1391
#define IDC_COMBO_ALIGNMENT_TYPE4       1391
#define IDC_COMBO_INSP_METHOD           1391
#define IDC_EDIT_SOBEL_THRESHOLD4       1392
#define IDC_COMBO_INSP_SUB_METHOD       1392
#define IDC_CHK_BLACK_PANEL_CHECK2      1393
#define IDC_EDIT_PROJECTION_AREA_LEFT   1393
#define IDC_CHK_REVERSE_PANEL_CHECK     1394
#define IDC_COMBO_ANGLE_CALC_METHOD     1394
#define IDC_EDIT_PROJECTION_AREA_LEFT2  1395
#define IDC_COMBO_MANUAL_MARK_COUNT     1395
#define IDC_LIST                        1396
#define IDC_EDIT_PROJECTION_AREA_RIGHT  1396
#define IDC_CHK_ENABLE_AUTO_ROI         1397
#define IDC_EDIT_PROJECTION_AREA_RIGHT2 1398
#define IDC_CHK_ENABLE_AUTO_ROI2        1399
#define IDC_COMBO_ALIGNMENT_TYPE3       1399
#define IDC_COMBO_DUMMY_CORNER_INSP_CAM 1399
#define IDC_CHK_ENABLE_WHITE_DUST       1400
#define IDC_CB_SELECT_CAMERA3           1401
#define IDC_COMBO_DUMMY_CORNER_INSP_DIR 1401
#define IDC_COMBO_DUMMY_CORNER_FILTER   1401
#define IDC_STATIC_ROI_SIZE_X           1403
#define IDC_CHK_ENABLE_WHITE_DUST2      1404
#define IDC_CHK_ENABLE_BLACK_CHIP       1405
#define IDC_STATIC_ROI_SIZE_Y           1406
#define IDC_CHK_ENABLE_BLACK_CHIP2      1407
#define IDC_CHK_ENABLE_PEELER_INSP      1408
#define IDC_EDIT_ROI_SIZE_X             1409
#define IDC_CHK_ENABLE_PEELER_INSP2     1410
#define IDC_EDIT_ROI_SIZE_Y             1411
#define IDC_COMBO_ALIGNMENT_TYPE2       1412
#define IDC_COMBO_ALIGNMENT_DIR         1413
#define IDC_STATIC_ROI_CENTER_OFFSET_X  1414
#define IDC_CHK_ENABLE_PEELER_INSP3     1415
#define IDC_CHK_ENABLE_PREMOLD_INSP     1416
#define IDC_STATIC_ROI_CENTER_OFFSET_Y  1417
#define IDC_CHK_ENABLE_PREMOLD_INSP2    1418
#define IDC_CHK_ENABLE_OVERFLOW_INSP    1419
#define IDC_EDIT_ROI_CENTER_OFFSET_X    1420
#define IDC_STATIC_MARK_FIND_METHOD2    1421
#define IDC_EDIT_ROI_CENTER_OFFSET_X2   1422
#define IDC_EDIT_ROI_CENTER_OFFSET_Y    1423
#define IDC_SLIDER_LIGHT_SETTING        1424
#define IDC_SLIDER_LIGHT_SETTING2       1425
#define IDC_STATIC_MARK_FIND_METHOD3    1425
#define IDC_SLIDER_EXPOSURE_SETTING     1425
#define IDC_CB_SELECT_IMAGE_PROC2       1426
#define IDC_CHK_REVERSE_PANEL_CHECK2    1427
#define IDC_CHK_USE_ALIGN_IMAGE         1428
#define IDC_CB_SELECT_IMAGE_PROC3       1429
#define IDC_CB_SELECT_LIGHT_CHANNEL     1430
#define IDC_CB_SELECT_LIGHT_CHANNEL2    1431
#define IDC_CB_LIGHT_INDEX              1431
#define IDC_STATIC_CALIBRATION_TYPE     1431
#define IDC_COMBO2                      1432
#define IDC_STATIC_MODEL_PANEL_TYPE     1432
#define IDC_COMBO_SELECT_INSP_POS       1432
#define IDC_COMBO_INSP_SPEC             1432
#define IDC_CB_SELECT_LIGHT_CHANNEL3    1432
#define IDC_CB_SELECT_USER_SET          1432
#define IDC_COMBO_CALIBRATION_TYPE      1433
#define IDC_COMBO_INSP_SUB_SPEC         1433
#define IDC_COMBO_MODEL_PANEL_TYPE      1434
#define IDC_COMBO_INSP_SCAN_POS         1434
#define IDC_STATIC_PLC_INTERFACE        1435
#define IDC_COMBO_INSP_ITEM_LIST        1435
#define IDC_STATIC_MARK_FIND_METHOD4    1436
#define IDC_COMBO_ELB_TRACE_PARAMETER   1436
#define IDC_STATIC_PLC_READ_0           1437
#define IDC_COMBO_INSP_ITEM_LIST2       1437
#define IDC_BTN_RECALC_REF_POS          1438
#define IDC_BUTTON_OK                   1439
#define IDC_CHK_ENABLE_AUTO_ROI3        1440
#define IDC_CHK_ENABLE_FIND_NEW_ROI     1441
#define IDC_STATIC_PLC_WRITE_0          1442
#define IDC_BTN_RECALC_REVISION_POS     1443
#define IDC_COMBO_DOPO_START_PT         1444
#define IDC_STATIC_PLC_READ_1           1445
#define IDC_STATIC_RECALC_REF_POS_X     1446
#define IDC_COMBO_DOPO_START_PT2        1447
#define IDC_COMBO_DOPO_END_PT           1448
#define IDC_STATIC_PLC_READ_2           1449
#define IDC_STATIC_RECALC_REF_POS_Y     1450
#define IDC_CHK_ENABLE_ALIGN_MEASURE_SPEC_OUT_JUDGE2 1451
#define IDC_CHK_ENABLE_REVIEW           1452
#define IDC_STATIC_PLC_READ_3           1453
#define IDC_STATIC_RECALC_REVISION_POS_X 1454
#define IDC_CHK_RANSAC_DIR_0_0          1455
#define IDC_CB_CORNER_TYPE0             1456
#define IDC_STATIC_PLC_READ_4           1457
#define IDC_STATIC_RECALC_REVISION_POS_X2 1458
#define IDC_STATIC_RECALC_REVISION_POS_Y 1459
#define IDC_CB_CORNER_TYPE1             1460
#define IDC_EDIT_MODEL_NAME             1461
#define IDC_STATIC_PLC_READ_5           1462
#define IDC_BUTTON4                     1463
#define IDC_BTN_ADD_CALIB_POINT         1464
#define IDC_BTN_CLEAR_DATA              1465
#define IDC_STATIC_PLC_READ_6           1466
#define IDC_LIST1                       1467
#define IDC_LIST_NETWORK                1467
#define IDC_LIST_LOG                    1467
#define IDC_LIST_SCRIPT_LIST            1467
#define IDC_LIST_MANUAL_CALIBRATION     1468
#define IDC_LIST_SCRIPT_LIST2           1468
#define IDC_LIST_SCRIPT_HISTORY         1468
#define IDC_CHK_RANSAC_DIR_0_1          1469
#define IDC_CB_EDGE_POLARITY1           1470
#define IDC_STATIC_PLC_READ_7           1471
#define IDC_CHK_ENABLE_L_CHECK          1472
#define IDC_STATIC_PLC_READ_8           1473
#define IDC_CHK_ENABLE_REVISION_REVERSE_X 1473
#define IDC_STATIC_L_CHECK_TOLERANCE    1474
#define IDC_STATIC_PLC_READ_9           1475
#define IDC_STATIC_LCHECK_SCALE         1475
#define IDC_EDITL_CHECK_LIMIT           1476
#define IDC_CHK_ENABLE_REVISION_REVERSE_Y 1476
#define IDC_EDIT_L_CHECK_TOLERANCE      1477
#define IDC_STATIC_PLC_WRITE_1          1478
#define IDC_EDIT_L_CHECK_TOLERANCE2     1478
#define IDC_EDIT_LCHECK_SCALE           1478
#define IDC_STATIC_LCHECK_TITLE         1479
#define IDC_CHK_ENABLE_REVISION_REVERSE_T 1479
#define IDC_CHK_USE_4POINT_ALIGN        1480
#define IDC_CHK_ENABLE_REVISION_REVERSE_Y2 1480
#define IDC_CHK_ENABLE_REVISION_REVERSE_XY 1480
#define IDC_STATIC_PLC_WRITE_2          1481
#define IDC_CHK_USE_4POINT_ALIGN2       1481
#define IDC_CHK_USE_CRACK_INSP          1481
#define IDC_EDIT_LCHECK                 1482
#define IDC_CHK_USE_CRACK_INSP2         1482
#define IDC_CHK_USE_INCLUDED_ANGLE      1482
#define IDC_CHK_USING_1CAM              1483
#define IDC_STATIC_L_CHECK_REFERENCE    1483
#define IDC_STATIC_PLC_WRITE_3          1484
#define IDC_CHK_USE_DUMMY_CORNER_INSP   1484
#define IDC_BUTTON5                     1485
#define IDC_CHK_USE_BOX_INSP            1485
#define IDC_BTN_CALCULATE_LCHECK        1486
#define IDC_CHK_USE_DUMMY_SEPAR_INSP    1486
#define IDC_CHK_USING_1CAM2             1487
#define IDC_CHK_USE_INCLUDED_ANGLE2     1487
#define IDC_CHK_USE_MULTIPLEX_ROI       1487
#define IDC_CHK_ENABLE_2SHOT_ALIGN      1488
#define IDC_CHK_USE_FIXTURE_MARK        1488
#define IDC_STATIC_PLC_READ_10          1489
#define IDC_STATIC_L_CHECK_SPEC         1489
#define IDC_EDIT_L_CHECK_SPEC           1490
#define IDC_CHK_RANSAC_DIR_1_0          1491
#define IDC_STATIC_L_CHECK_SPEC_Y       1491
#define IDC_CB_EDGE_DIRECTION0          1492
#define IDC_STATIC_PLC_WRITE_4          1493
#define IDC_CB_PRE_PROCESS1             1493
#define IDC_CB_EDGE_PROCESS1            1494
#define IDC_CHK_RANSAC_DIR_1_1          1495
#define IDC_CB_EDGE_PROCESS2            1495
#define IDC_CHK_USE_SUB_METHOD          1495
#define IDC_CHK_USE_POST_INSP           1495
#define IDC_CB_EDGE_DIRECTION1          1496
#define IDC_CHK_USE_POST_INSP2          1496
#define IDC_CHK_USE_DUST_INSP           1496
#define IDC_STATIC_PLC_WRITE_5          1497
#define IDC_CB_PRE_PROCESS2             1497
#define IDC_CHK_USE_REALTIME_TRACE      1497
#define IDC_EDIT_THETA_OFFSET           1498
#define IDC_EDIT_REVISION_OFFSET_T      1498
#define IDC_STATIC_PLC_WRITE_6          1499
#define IDC_EDIT_REVISION_OFFSET_Y      1499
#define IDC_LB_CHESS_X2                 1499
#define IDC_STATIC_LIMIT_OFFSET         1500
#define IDC_EDIT_REVISION_OFFSET_X      1500
#define IDC_EDIT_REVISION_OFFSET_T3     1500
#define IDC_LB_CHESS_Y2                 1500
#define IDC_CHK_RANSAC_DIR_3_0          1501
#define IDC_CHK_USE_CYCLE_TRACE         1501
#define IDC_STATIC_REMOVE_NOISE_SIZE3   1502
#define IDC_CHK_USE_DUST_INSP2          1502
#define IDC_CHK_USE_REVERSE_ORDER       1502
#define IDC_STATIC_PLC_WRITE_7          1503
#define IDC_CHK_USE_METAL_TRACE2        1503
#define IDC_CHK_USE_SUB_INSP_ALGORITHM  1503
#define IDC_EDIT_LIMIT_OFFSET           1504
#define IDC_CHK_USE_REVERSE_ORDER2      1504
#define IDC_CHK_USE_AUTOSAVE_AVI        1504
#define IDC_CHK_RANSAC_DIR_3_1          1505
#define IDC_CHK_USE_AUTOSAVE_AVI2       1505
#define IDC_CHK_USE_BM_BASE             1505
#define IDC_STATIC_REMOVE_NOISE_SIZE4   1506
#define IDC_CHK_USE_BOX_INSP2           1506
#define IDC_CHK_USE_INPUT_INSP          1506
#define IDC_BTN_SYSTEM_OPTION           1507
#define IDC_CHK_USE_REFERENCE_MARK      1507
#define IDC_STATIC_PLC_WRITE_8          1508
#define IDC_EDIT_GRAB_DELAY             1508
#define IDC_STATIC_SEARCH_POS_OFFSET1   1509
#define IDC_STATIC_PLC_WRITE_9          1510
#define IDC_EDIT_SEARCH_POS_OFFSET1     1511
#define IDC_STATIC_PLC_READ_11          1512
#define IDC_STATIC_MANUAL_INPUT_VIEWER  1513
#define IDC_STATIC_SEARCH_RANGE1        1514
#define IDC_STATIC_PLC_READ_12          1515
#define IDC_STATIC_MANUAL_INPUT_VIEWER2 1516
#define IDC_EDIT_SEARCH_RANGE1          1517
#define IDC_STATIC_PLC_READ_13          1518
#define IDC_STATIC_MANUAL_INPUT_MARK_TITLE 1519
#define IDC_STATIC_SEARCH_THRESHOLD1    1520
#define IDC_STATIC_PLC_READ_14          1521
#define IDC_EDIT_SEARCH_THRESHOLD1      1522
#define IDC_STATIC_PLC_WRITE_10         1523
#define IDC_STATIC_MANUAL_MINI_VIEWER1  1524
#define IDC_STATIC_SEARCH_EDGE_COLOR1   1525
#define IDC_STATIC_PLC_WRITE_11         1526
#define IDC_STATIC_MANUAL_MINI_VIEWER2  1527
#define IDC_EDIT_SEARCH_POS_OFFSET2     1528
#define IDC_STATIC_PLC_WRITE_12         1529
#define IDC_STATIC_SEARCH_DIRECTION1    1530
#define IDC_STATIC_PLC_WRITE_13         1531
#define IDC_EDIT_SEARCH_RANGE2          1532
#define IDC_STATIC_PLC_WRITE_14         1533
#define IDC_EDIT_SEARCH_THRESHOLD2      1534
#define IDC_EDIT_SEARCH_POS_OFFSET3     1535
#define IDC_EDIT_SEARCH_RANGE3          1536
#define IDC_EDIT_SEARCH_THRESHOLD3      1537
#define IDC_CHK_RANSAC_DIR_2_0          1538
#define IDC_STATIC_SOBEL_THRESHOLD3     1539
#define IDC_STATIC_SEARCH_TITLE         1540
#define IDC_STATIC_SIDE1                1541
#define IDC_STATIC_SIDE2                1542
#define IDC_STATIC_SIDE3                1543
#define IDC_CHK_ENABLE_CALIB_MARKCOPY   1544
#define IDC_STATIC_SEARCH_TITLE2        1545
#define IDC_STATIC_SEARCH_X             1546
#define IDC_STATIC_SEARCH_OUT           1547
#define IDC_AUTO_RESULT_GRAPH           1548
#define IDC_STATIC_SEARCH_IN            1549
#define IDC_STATIC_LEFT_DIR             1550
#define IDC_CHK_RANSAC_DIR_1_3          1551
#define IDC_CHK_RANSAC_DIR_2_1          1552
#define IDC_STATIC_SOBEL_THRESHOLD4     1553
#define IDC_STATIC_LEFT_DIR2            1554
#define IDC_STATIC_RIGHT_DIR            1555
#define IDC_EDIT_SOBEL_THRESHOLD5       1556
#define IDC_EDIT_SOBEL_THRESHOLD6       1557
#define IDC_EDIT_GLASS_INCH             1558
#define IDC_STATIC_GLASS_INCH           1559
#define IDC_STATIC_1                    1560
#define IDC_STATIC_ALIGNMENT_TARGET     1561
#define IDC_STATIC_2                    1562
#define IDC_STATIC_ANGLE_CALC_METHOD    1562
#define IDC_STATIC_3                    1563
#define IDC_STATIC_ALIGNMENT_TYPE       1564
#define IDC_STATIC_THETA_REFERENCE      1565
#define IDC_STATIC_INSP_METHOD          1565
#define IDC_STATIC_4                    1566
#define IDC_STATIC_INSP_SUB_METHOD      1566
#define IDC_STATIC_ENABLE_ALIGN_MEASURE 1567
#define IDC_STATIC_5                    1568
#define IDC_STATIC_ENABLE_ALIGN_MEASURE_SPEC_OUT_NG 1569
#define IDC_STATIC_6                    1570
#define IDC_STATIC_ENABLE_ALIGN_LEFT_RIGHT_DIFF_JUDGE 1571
#define IDC_STATIC_ENABLE_ALIGN_LEFT_RIGHT_DIFF_SPEC 1572
#define IDC_STATIC_NG                   1573
#define IDC_STATIC_ENABLE_ALIGN_LEFT_RIGHT_DIFF_SPEC2 1574
#define IDC_STATIC_PANEL_SELECT         1575
#define IDC_STATIC_ENABLE_ALIGN_LEFT_RIGHT_DIFF_SPEC3 1576
#define IDC_STATIC_PANEL_REVERSE        1577
#define IDC_STATIC_OK                   1578
#define IDC_STATIC_ENABLE_AUTOROI       1579
#define IDC_STATIC_OK_GY                1580
#define IDC_STATIC_WHITE_DUST           1581
#define IDC_STATIC_NG_GY                1582
#define IDC_STATIC_ENABLE_L_CHECK       1583
#define IDC_STATIC_TOTAL                1584
#define IDC_STATIC_ENABLE_REVISION_REVERSE_X 1584
#define IDC_STATIC_BLACK_CHIP           1585
#define IDC_STATIC_ENABLE_REVISION_REVERSE_Y 1585
#define IDC_STATIC_TOTAL_GY             1586
#define IDC_STATIC_ENABLE_REVISION_REVERSE_T 1586
#define IDC_STATIC_PEELER_INSP          1587
#define IDC_STATIC_ENABLE_REVISION_REVERSE_XY 1587
#define IDC_STATIC_PEELER_INSP2         1588
#define IDC_STATIC_ALIGNMENT_DIRECTION  1589
#define IDC_STATIC_PREMOLD_INSP         1590
#define IDC_STATIC_OVERFLOW_INSP        1591
#define IDC_STATIC_USE_ALIGN_IMAGE      1592
#define IDC_STATIC_ENABLE_AUTOROI2      1593
#define IDC_STATIC_ENABLE_REVIEW        1594
#define IDC_STATIC_NG_DAY               1595
#define IDC_STATIC_CORNER_TYPE0         1596
#define IDC_STATIC_CORNER_TYPE1         1597
#define IDC_STATIC_OK_DAY               1598
#define IDC_STATIC_EDGE_FIND_DIRECTION  1599
#define IDC_STATIC_MODEL_SELECT_CAM     1599
#define IDC_STATIC_EDGE_POLARITY0       1600
#define IDC_STATIC_EDGE_POLARITY1       1601
#define IDC_STATIC_TOTAL_DAY            1602
#define IDC_STATIC_MODEL_SELECT_POS     1602
#define IDC_STATIC_EDGE_DIRECTION0      1603
#define IDC_STATIC_EDGE_DIRECTION1      1604
#define IDC_STATIC_NG_SW                1605
#define IDC_STATIC_PRE_PROCESS1         1605
#define IDC_STATIC_OK_SW                1606
#define IDC_STATIC_PRE_PROCESS2         1606
#define IDC_STATIC_TOTAL_SW             1607
#define IDC_STATIC_EDGE_PROCESS1        1607
#define IDC_STATIC_NG_TOTAL             1608
#define IDC_STATIC_EDGE_PROCESS2        1608
#define IDC_STATIC_OK_TOTAL             1609
#define IDC_STATIC_TOTAL_TOTAL          1610
#define IDC_STATIC_NG_PERCENT           1611
#define IDC_STATIC_OK_PERCENT           1612
#define IDC_STATIC_TOTAL_PERCENT        1613
#define IDC_STATIC_DAILY_PRODUCTION     1614
#define IDC_STATIC_INSPECTION           1615
#define IDC_BTN_ADD                     1616
#define IDC_STATIC_SPEC                 1616
#define IDC_BTN_SUB                     1617
#define IDC_STATIC_SPEC2                1617
#define IDC_STATIC_MICROFLUDIC_VALUE    1617
#define IDC_BTN_EQUAL                   1618
#define IDC_STATIC_LEFT_PANEL_JUDGE     1618
#define IDC_NUMBER_TEXT                 1619
#define IDC_STATIC_MICROFLUDIC_VALUE3   1619
#define IDC_STATIC_RIGHT_PANEL_JUDGE    1619
#define IDC_KEY_1                       1620
#define IDC_BTN_AUTO_MEMORY             1620
#define IDC_KEY_2                       1621
#define IDC_STATIC_MICROFLUDIC_VALUE2   1621
#define IDC_KEY_3                       1622
#define IDC_BTN_AUTO_CPU                1622
#define IDC_KEY_4                       1623
#define IDC_BTN_AUTO_CDRIVE             1623
#define IDC_KEY_5                       1624
#define IDC_BTN_AUTO_DDRIVE             1624
#define IDC_KEY_6                       1625
#define IDC_KEY_7                       1626
#define IDC_KEY_8                       1627
#define IDC_KEY_9                       1628
#define IDC_KEY_BACK_SPACE              1629
#define IDC_KEY_0                       1630
#define IDC_KEY_DOT                     1631
#define IDC_KEY_PLUS_MINUS              1632
#define IDC_CALCUL_TEXT                 1633
#define IDC_EDIT_COPYDATA_X             1634
#define IDC_BUTTON_COPYDATA_Y           1635
#define IDC_BUTTON_COPYDATA_Z           1636
#define IDC_BUTTON_COPYDATA_TH          1637
#define IDC_BTN_PREALIGN_TEST           1638
#define IDC_EDIT_COPYDATA_Y             1639
#define IDC_EDIT_COPYDATA_Z             1640
#define IDC_EDIT_COPYDATA_TH            1641
#define IDC_PIC_RANSAC                  1642
#define IDC_EDIT_LIGHT_SETTING_EXIST    1643
#define IDC_SLIDER_LIGHT_SETTING_EXIST  1644
#define IDC_SPLIT1                      1647
#define IDC_STATIC_VIEWER_BASE_MAIN     1648
#define IDC_BTN_DLG_ORIGINAL_IMAGE      1650
#define IDC_BTN_DLG_CENTER_LINE         1651
#define IDC_BTN_DLG_FIT_IMAGE           1652
#define IDC_BTN_DLG_ZOOM_IN             1653
#define IDC_BTN_DLG_ZOOM_OUT            1654
#define IDC_BTN_DLG_DRAW_AREA           1655
#define IDC_BTN_DLG_MOVE                1655
#define IDC_STATIC_VIEWER_BASE_MACHINE  1656
#define IDC_BTN_DLG_CENTER_LINE2        1656
#define IDC_BTN_DLG_SHOW_OVERLAY        1656
#define IDC_GRUOP_ALING_FUNCTION        1657
#define IDC_GROUP_ALIGN_TYPE            1658
#define IDC_GROUP_GLASS                 1659
#define IDC_GRUOP_LCHECK                1659
#define IDC_GROUP_CALIBRATION           1660
#define IDC_EXIST_FUNCTION              1661
#define IDC_GROUP_REVISION              1663
#define IDC_STATIC_PROCESS_PLC_HISTORY  1664
#define IDC_TAB_ALGOLIST                1664
#define IDC_ELB_INSPECTION              1664
#define IDC_BTN_CALIB_SAVE              1665
#define IDC_DISTANCE_FUNCTION           1665
#define IDC_MODEL_ALGOLIST              1666
#define IDC_CHK_ENABLE_PROFILE          1667
#define IDC_LB_SQUARE_SIZE              1668
#define IDC_BTN_SET_SUB_MARK            1669
#define IDC_GRID_PLC_DATA               1670
#define IDC_LB_MARK_OFFSET_X_TITLE      1670
#define IDC_GRID_SELECT_VIEWER          1671
#define IDC_STATIC_VIEWER1              1672
#define IDC_LB_MARK_OFFSET_X            1672
#define IDC_STATIC_VIEWER2              1673
#define IDC_LB_MARK_OFFSET_Y            1673
#define IDC_GRID_NUM_OF_USING_LIGHT_DATA 1674
#define IDC_GRID_JOB_LIGHT_DATA         1674
#define IDC_CHK_SUB_INSP                1674
#define IDC_STATIC_VIEWER3              1675
#define IDC_STATIC_VIEWER9              1676
#define IDC_EDIT_JOB_COUNT_MODIFY       1678
#define IDC_STATIC_VIEWER4              1679
#define IDC_GRID_JOB_VIEWER             1680
#define IDC_STATIC_VIEWER5              1681
#define IDC_GRID_JOB_CAM_VIEWER         1682
#define IDC_GRID_JOB_LIGHT_INDEX_NAME_VIEWER 1683
#define IDC_STATIC_SELECT_INI2          1684
#define IDC_STATIC_VIEWER7              1685
#define IDC_STATIC_VIEWER6              1686
#define IDC_GRID_LIGHT_CONTROL_VIEWER   1687
#define IDC_GRID_CAMERA_VIEWER          1688
#define IDC_EDIT_LIGHT_CONTROL_MODIFY   1690
#define IDC_STATIC_ALGO_COUNT3          1692
#define IDC_EDIT_VIEWER_COUNT_MODIFY    1693
#define IDC_STATIC_ALGO_COUNT4          1694
#define IDC_STATIC_ALGO_COUNT5          1695
#define IDC_STATIC_INSP_SUB_INTERVAL    1696
#define IDC_STATIC_INSP_SUB_INTERVAL_TOL 1697
#define IDC_STATIC_INSP_SUB_DIRECTION   1698
#define IDC_EDIT_VIEWER_COUNT_X         1698
#define IDC_EDIT_INSP_SUB_INTERVAL      1699
#define IDC_EDIT_VIEWER_COUNT_Y         1699
#define IDC_EDIT_INSP_SUB_INTERVAL_TOL  1700
#define IDC_GRID_JOB_VIEW_VIEWER        1700
#define IDC_COMBO_INSP_SUB_DIRECTION    1701
#define IDC_STATIC_VIEWER10             1701
#define IDC_DISTANCE_SUB_FUNCTION       1702
#define IDC_GRID_JOB_MACHINE_VIEWER     1702
#define IDC_PIC_SEARCH_VIEW             1703
#define IDC_GB_INSPECTION_SPEC          1703
#define IDC_STATIC_VIEWER11             1703
#define IDC_SCROLL_LOAD_V               1704
#define IDC_DISTANCE_SUB_FUNCTION3      1704
#define IDC_GB_INSPECTION_PARA          1704
#define IDC_EDIT_CAMERA_COUNT           1704
#define IDC_SCROLL_LOAD_H               1705
#define IDC_GB_INSPECTION_SPEC_PARAMETER 1705
#define IDC_STATIC_VIEWER12             1705
#define IDC_BTN_IMG_LOAD                1706
#define IDC_CUSTOM1                     1706
#define IDC_GRID_SPEC_VIEWER            1706
#define IDC_GB_TRACE_IMAGE_PARAMETER    1706
#define IDC_CUSTOM_DAILY_REPORT         1706
#define IDC_GRID_SERVER_VIEWER          1706
#define IDC_GRAPHIC_DISPLAY             1706
#define IDC_BTN_ORIGINAL                1707
#define IDC_GRID_SPEC_VIEWER2           1707
#define IDC_GRID_REF_DATA_VIEWER        1707
#define IDC_GB_INSPECTION_PARA2         1707
#define IDC_GB_DIFF_INSPECTION_PARA     1707
#define IDC_CUSTOM_DAILY_REPORT2        1707
#define IDC_GRID_JOB_CALIPER_VIEWER     1707
#define IDC_BTN_MANUAL_ROTATE           1708
#define IDC_GB_ELB_TRACE_PARAMETER      1708
#define IDC_STATIC_VIEWER13             1708
#define IDC_GRID_INSP_SPEC_VIEWER       1708
#define IDC_BTN_CALC_ROTATE             1709
#define IDC_GRID_INSP_RESULT_1          1709
#define IDC_EDIT_POS_MODIFY             1709
#define IDC_EDIT_L_CHECK_SPEC_Y         1710
#define IDC_BTN_MOVE_ROTATE             1710
#define IDC_GRID_JOB_POSITION_VIEWER    1710
#define IDC_GRID_REF_DATA_VIEWER2       1710
#define IDC_GRID_PRCO_TIME_VIEWER       1710
#define IDC_TAB_MAIN_VIEW               1711
#define IDC_STATIC_VIEWER14             1711
#define IDC_BTN_OFFSET_ROTATE           1711
#define IDC_BTN_SIMULATION_START        1712
#define IDC_GRID_INSP_RESULT_2          1712
#define IDC_STATIC_VIEWER15             1712
#define IDC_BTN_SIMULATION_STOP         1713
#define IDC_GRID_JOB_MAIN_VIEWER        1713
#define IDC_TAB_SPECVIEW                1714
#define IDC_EDIT_CAMERA_COUNT_MODIFY    1714
#define IDC_CHECK_SHOW_MASK             1715
#define IDC_EDIT_MACHINE_COUNT_X        1715
#define IDC_GRID_INSP_RESULT_3          1716
#define IDC_STATIC_ORG_START            1716
#define IDC_CHECK_SHOW_PREPROC          1716
#define IDC_EDIT_MACHINE_COUNT_Y        1716
#define IDC_STATIC_ORG_END              1717
#define IDC_CHECK_ABLE_IGNORE           1717
#define IDC_TAB_RESULTVIEW              1717
#define IDC_EDIT_MAIN_COUNT_X           1717
#define IDC_CHECK_SHOW_TRACKER          1717
#define IDC_STATIC_AFTER_START          1718
#define IDC_BTN_DRAW_AREA_MACHINE       1718
#define IDC_EDIT_MAIN_COUNT_Y           1718
#define IDC_STATIC_AFTER_END            1719
#define IDC_BTN_PATTERN_REGIST_MACHINE  1719
#define IDC_EDIT_USE_LIGHT              1719
#define IDC_BTN_PATTERN_VIEW_MACHINE    1720
#define IDC_STATIC_POSITION_COUNT       1720
#define IDC_BTN_PATTERN_SEARCH_MACHINE  1721
#define IDC_STATIC_MAIN_X               1721
#define IDC_MFCPROPERTYGRID_INSPECTION  1722
#define IDC_STATIC_MAIN_Y               1722
#define IDC_BTN_SYSTEMOPTION            1723
#define IDC_STATIC_CAMERA_COUNT         1723
#define IDC_STATIC_MACHINE_X            1724
#define IDC_STATIC_MACHINE_Y            1725
#define IDC_STATIC_CALIPER_CAM          1726
#define IDC_STATIC_CALIPER_POS          1727
#define IDC_STATIC_USE_LIGHT_CNT        1728
#define IDC_GRID_PLC_ADDRESS_VIEWER     1729
#define IDC_STATIC_VIEWER16             1730
#define IDC_STATIC_START_LIGHT_CTRL_ID  1731
#define IDC_STATIC_START_CHANNEL_CTRL_ID 1732
#define IDC_STATIC_START_CAMERA_INDEX   1733
#define IDC_STATIC_NETWORK_ADPTTER      1734
#define IDC_STATIC_VIEWER17             1735
#define IDC_STATIC_VIEWER18             1736
#define IDC_STATIC_CAMERA_NAME          1737
#define IDC_GROUP_VIEWER_INI            1753
#define IDC_STATIC_VIEWER_COUNT         1754
#define IDC_STATIC_VIEWER_COUNT_X       1755
#define IDC_STATIC_VIEWER_COUNT_Y       1756
#define IDC_GROUP_CAMERA_INI            1757
#define IDC_STATIC_CAMERA_COUNT2        1758
#define IDC_STATIC_270                  1759
#define IDC_STATIC_0                    1760
#define IDC_STATIC_180                  1761
#define IDC_STATIC_90                   1762
#define IDC_GROUP_ALIGN_INI             1763
#define IDC_STATIC_0ITEC                1764
#define IDC_STATIC_1TSM                 1765
#define IDC_STATIC_2ITEC                1766
#define IDC_STATIC_3LLIGHT              1767
#define IDC_STATIC_4LLIGHT              1768
#define IDC_STATIC_5LLIGHT              1769
#define IDC_STATIC_6LLIGHT              1770
#define IDC_GROUP_PLC_INI               1771
#define IDC_PROGRESS_CPU                1772
#define IDC_STATIC_OFFSET_X             1772
#define IDC_PROGRESS_MEMORY             1773
#define IDC_STATIC_OFFSET_Y             1773
#define IDC_EDIT_INSP_LX                1773
#define IDC_PROGRESS_CDRIVE             1774
#define IDC_EDIT_OFFSET_X               1774
#define IDC_EDIT_INSP_LY                1774
#define IDC_BTN_DAILY_CLEAR             1775
#define IDC_EDIT_OFFSET_Y               1775
#define IDC_EDIT_INSP_RX                1775
#define IDC_PROGRESS_DDRIVE             1776
#define IDC_STATIC_JOB                  1776
#define IDC_EDIT_INSP_RY                1776
#define IDC_BTN_DAILY_CLEAR2            1777
#define IDC_EDIT_JOB                    1777
#define IDC_EDIT_SCOPE_LX               1777
#define IDC_LB_TREND_VIEW_TITLE         1778
#define IDC_STATIC_TARGET_X             1778
#define IDC_EDIT_SCOPE_LY               1778
#define IDC_STATIC_VIEWER_BASE_TREND    1779
#define IDC_STATIC_TARGET_Y             1779
#define IDC_EDIT_SCOPE_RX               1779
#define IDC_CUSTOM_TREND_CHART          1780
#define IDC_STATIC_TARGET_ORIGIN_X      1780
#define IDC_EDIT_SCOPE_RY               1780
#define IDC_STATIC_TARGET_ORIGIN_Y      1781
#define IDC_STATIC_INSP_LX              1781
#define IDC_STATIC_INSP_LY              1782
#define IDC_EDIT_TARGET_X               1783
#define IDC_STATIC_INSP_RX              1783
#define IDC_EDIT_TARGET_Y               1784
#define IDC_STATIC_INSP_RY              1784
#define IDC_EDIT_RESULT_X               1785
#define IDC_STATIC_SCOPE_LX             1785
#define IDC_EDIT_RESULT_Y               1786
#define IDC_STATIC_SCOPE_LY             1786
#define IDC_STATIC_RESULT_Y             1787
#define IDC_STATIC_SCOPE_RX             1787
#define IDC_STATIC_RESULT_X             1788
#define IDC_STATIC_SCOPE_RY             1788
#define IDC_EDIT_TARGET_ORIGIN_X        1789
#define IDC_STATIC_SCALE_LX             1789
#define IDC_EDIT_TARGET_Y2              1790
#define IDC_EDIT_TARGET_ORIGIN_Y        1790
#define IDC_STATIC_SCALE_LY             1790
#define IDC_STATIC_SCALE_RX             1791
#define IDC_EDIT_CAM                    1792
#define IDC_STATIC_SCALE_RY             1792
#define IDC_STATIC_CAM                  1793
#define IDC_EDIT_SCALE_LX               1793
#define IDC_EDIT_POS                    1794
#define IDC_EDIT_SCALE_LY               1794
#define IDC_STATIC_POS                  1795
#define IDC_EDIT_SCALE_RX               1795
#define IDC_EDIT_SCALE_RY               1796
#define IDC_EDIT_SCALE                  1798
#define IDC_GRID_LIST                   1799
#define IDC_STATIC_LIST_TITLE           1803
#define IDC_LB_LIST_TITLE               1803
#define IDC_BUTTON_RUDOT                1804
#define IDC_LIST_REGIST_ID              1804
#define IDC_BTN_CONFIRM                 1804
#define IDC_BUTTON_1                    1805
#define IDC_STATIC_LOGIN_INFO           1805
#define IDC_BUTTON_2                    1806
#define IDC_STATIC_LOGIN_NAME           1806
#define IDC_BUTTON_3                    1807
#define IDC_EDIT_LOGIN_NAME             1807
#define IDC_BUTTON_4                    1808
#define IDC_EDIT_LOGIN_NAME2            1808
#define IDC_EDIT_LOGIN_PASSWORD         1808
#define IDC_BTN_SELECT_POSITION1        1808
#define IDC_BTN_SELECT                  1808
#define IDC_BUTTON_5                    1809
#define IDC_STATIC_LOGIN_LEVEL          1809
#define IDC_BTN_SELECT_POSITION2        1809
#define IDC_BUTTON_6                    1810
#define IDC_STATIC_LOGIN_PASSWORD       1810
#define IDC_STATIC_BTN_TOP_1CAM         1810
#define IDC_LB_SELECET                  1810
#define IDC_BUTTON_7                    1811
#define IDC_STATIC_BTN_LEFT_1CAM        1811
#define IDC_BUTTON_8                    1812
#define IDC_STATIC_BTN_RIGHT_1CAM       1812
#define IDC_BUTTON_9                    1813
#define IDC_STATIC_BTN_BOTTOM_1CAM      1813
#define IDC_BUTTON_0                    1814
#define IDC_STATIC_LEFT_DIR_1CAM        1814
#define IDC_BUTTON_MINUS                1815
#define IDC_STATIC_RIGHT_DIR_1CAM       1815
#define IDC_BUTTON_EQUAL                1816
#define IDC_BTN_DLG_MOVE_1CAM           1816
#define IDC_BUTTON_BACKSP               1817
#define IDC_BTN_DLG_ZOOM_IN_1CAM        1817
#define IDC_BUTTON_Q                    1818
#define IDC_BTN_DLG_ZOOM_OUT_1CAM       1818
#define IDC_BUTTON_W                    1819
#define IDC_STATIC_MANUAL_INPUT_MARK_TITLE_1CAM 1819
#define IDC_BUTTON_E                    1820
#define IDC_STATIC_MANUAL_INPUT_VIEWER1_1CAM 1820
#define IDC_BUTTON_R                    1821
#define IDC_BTN_INPUT_COMPLETE_1CAM     1821
#define IDC_BUTTON_T                    1822
#define IDC_BTN_MANUAL_INPUT_NG_1CAM    1822
#define IDC_BUTTON_Y                    1823
#define IDC_STATIC_MANUAL_INPUT_VIEWER2_1CAM 1823
#define IDC_DATETIMEPICKER1             1823
#define IDC_DATETIMEPICKER_LIST         1823
#define IDC_BUTTON_U                    1824
#define IDC_STATIC_MANUAL_INPUT_VIEWER3_1CAM 1824
#define IDC_LB_VIEW_TITLE               1824
#define IDC_BUTTON_I                    1825
#define IDC_STATIC_MANUAL_INPUT_VIEWER4_1CAM 1825
#define IDC_LB_CONNECT_STATUS           1825
#define IDC_DATETIMEPICKER_START        1825
#define IDC_BUTTON_O                    1826
#define IDC_LB_MODEL                    1826
#define IDC_BUTTON_P                    1827
#define IDC_LB_POS_NAME                 1827
#define IDC_BUTTON_LB                   1828
#define IDC_LB_EQP_NAME                 1828
#define IDC_BUTTON_RB                   1829
#define IDC_LB_DLTIMEOUT                1829
#define IDC_BUTTON_TAB                  1830
#define IDC_LB_MC_TIMEOUT               1830
#define IDC_BUTTON_RS                   1831
#define IDC_LB_ATT_TIMEOUT              1831
#define IDC_BUTTON_A                    1832
#define IDC_EDIT_MODEL                  1832
#define IDC_BUTTON_S                    1833
#define IDC_EDIT_SCRIPT_RUN             1833
#define IDC_BUTTON_D                    1834
#define IDC_STATIC_SCRIPT_LIST          1834
#define IDC_BUTTON_F                    1835
#define IDC_STATIC_SCRIPT_COMMAND       1835
#define IDC_STATIC_NETWORK_INFO         1835
#define IDC_BUTTON_G                    1836
#define IDC_STATIC_GATE                 1836
#define IDC_BUTTON_H                    1837
#define IDC_STATIC_IP_ADDRESS           1837
#define IDC_BUTTON_J                    1838
#define IDC_STATIC_SUBNET_MASK          1838
#define IDC_BUTTON_K                    1839
#define IDC_EDIT_IP_ADDRESS             1839
#define IDC_BUTTON_L                    1840
#define IDC_BUTTON_SC                   1841
#define IDC_BUTTON_RUC                  1842
#define IDC_BUTTON_CR                   1843
#define IDC_BUTTON_ENTER                1844
#define IDC_BUTTON_Z                    1845
#define IDC_BUTTON_X                    1846
#define IDC_BUTTON_C                    1847
#define IDC_BUTTON_V                    1848
#define IDC_BUTTON_B                    1849
#define IDC_BUTTON_N                    1850
#define IDC_BUTTON_M                    1851
#define IDC_BUTTON_COMMA                1852
#define IDC_BUTTON_DOT                  1853
#define IDC_BUTTON_SLASH                1854
#define IDC_BUTTON_LSHIFT               1855
#define IDC_BUTTON_RSHIFT               1856
#define IDC_BUTTON_LCTRL                1857
#define IDC_BUTTON_ALT                  1858
#define IDC_BUTTON_SPACE                1859
#define IDC_BUTTON_HE                   1860
#define IDC_BUTTON_EXIT                 1861
#define IDC_EDIT_INPUT                  1862
#define IDC_BUTTON_CLEAR                1863
#define IDC_STATIC_ELB_INSP_RESULT_C    1864
#define IDC_EDIT_ELB_INSP_HOLE_C5       1865
#define IDC_EDIT_ELB_INSP_RESULT_C      1865
#define IDC_CHK_USE_DUST_INSP_ROI_SHAPE 1866
#define IDC_STATIC_DUST_INSP_ROI_SHAPE  1867
#define IDC_CHK_USE_METAL_TRACE_FIRST   1868
#define IDC_CHK_USE_METAL_TRACE         1869
#define IDC_GRID_SIMULATION_LIST        1902
#define IDC_BTN_SIMULATION_BOTTOM_START 1903
#define IDC_BTN_APPEND_LIST             1904
#define IDC_LB_SELECT_JOB               1906
#define IDC_LB_ALARM_MESSAGE            2115
#define IDC_TAB_CHARTVIEW               2116
#define IDC_CUSTOM_INSP_CHART           2117
#define IDC_CUSTOM_INSP_CHART2          2118
#define IDC_CUSTOM_INSP_CHART3          2119
#define IDC_CUSTOM_INSP_CHART4          2120
#define IDC_TAB_CHARTVIEW2              2121
#define ID_MENU_SHOW                    32771
#define ID_MENU_HIDE                    32772
#define ID_MENU_EXIST                   32773
#define ID_MENU_EIST                    32774
#define ID_MENU_EXIT                    32775
#define ID_PEN_1                        32777
#define ID_PEN_2                        32778
#define ID_PEN_3                        32779
#define ID_PEN_4                        32780
#define ID_BUTTON32780                  32780
#define ID_BRUSH                        32781
#define ID_BUTTON32781                  32781
#define ID_BUTTON_FIRST                 32781
#define ID_CROSS                        32781
#define ID_BUTTON32782                  32782
#define ID_BUTTON_SECOND                32782
#define ID_BUTTON32783                  32783
#define ID_BUTTON_THIRD                 32783
#define ID_BUTTON32784                  32784
#define ID_BUTTON_FOUR                  32784
#define ID_BUTTON32785                  32785
#define ID_BUTTON_LIVE                  32785
#define ID_BUTTON32786                  32786
#define ID_BUTTON_RECORD                32786
#define ID_BUTTON32787                  32787
#define ID_BUTTON_STOP                  32787
#define ID_DOGU_PEN                     32807
#define ID_DOGU_LINE                    32808
#define ID_DOGU_ELLIPSE                 32809
#define ID_DOGU_RECT                    32810
#define ID_DOGU_ERASE                   32812

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        208
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1840
#define _APS_NEXT_SYMED_VALUE           122
#endif
#endif
